server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://175.24.112.136:3306/web-oa?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: HUANGyungui+789

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    port: 6379
#    password: root
#    host: 192.168.125.128

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 搜索指定包别名
#  typeAliasesPackage: com.ruoyi.**.domain
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mappers/*Mapper.xml

#    mybatis配置
mybatis-plus:
  #  .xml映射地址   classpath*（表示其他依赖jar的类路径一起扫描）:/mapper/**/*.xml
  mapper-locations: classpath:/mappers/*.xml
  global-config:
    db-config:
      #  主键自增
      id-type: auto

logging:
  level:
    org.springfremework.web: info
    org.hibernate: error
  file:
    path: /log/web-love.log
    name: demo-log
